sensor:
  build: .
  dockerfile: Dockerfile.sensor
  net: host
  privileged: true
  volumes:
    - /var/log/maltrail

server:
  build: .
  dockerfile: Dockerfile.server
  ports: 
    - 8338:8338
  volumes_from:
    - sensor

test:
  image: alpine
  command: ping -c 1 136.161.101.53
